version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.3
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.4.3
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-data:/var/lib/kafka/data

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rails-app
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle-cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=sqlite3:storage/development.sqlite3
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BROKERS=kafka:29092
    depends_on:
      - kafka
      - redis
    stdin_open: true
    tty: true
    command: >
      bash -c "
        bundle install &&
        bin/rails db:prepare &&
        bin/dev
      "

  karafka:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: karafka-consumer
    volumes:
      - .:/rails
      - bundle-cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=sqlite3:storage/development.sqlite3
      - REDIS_URL=redis://redis:6379/0
      - KAFKA_BROKERS=kafka:29092
    depends_on:
      - kafka
      - redis
      - web
    command: >
      bash -c "
        bundle install &&
        bundle exec karafka server
      "

volumes:
  zookeeper-data:
  zookeeper-logs:
  kafka-data:
  redis-data:
  bundle-cache:
